output_display: null
visualizer_layout: 7
rotate: 0
framerate: 20
spi_speed_hz: 16000000
dc_pin: 25
rst_pin: 27
backlight_pin: null
touch_enabled: true
touch_rotate: 0
touch_x_min: 300
touch_x_max: 3800
touch_y_min: 300
touch_y_max: 3800
